create table USERS (
  commentid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username varchar(256),
  password varchar(256),
  enabled boolean
);

create table AUTHORITIES (
  username varchar(256),
  authority varchar(256)
);

create TABLE posts (
  postid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lilname varchar(200),
  fullname varchar(200),
  userid BIGINT,
  content varchar(10000),
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

create table TAGS (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tagname varchar(20)
);

create TABLE COMMENTS (
  commentid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  postid BIGINT,
  userid BIGINT,
  score INTEGER DEFAULT 0,
  lilname varchar(100),
  content varchar(250),
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

create TABLE POSTS_TAGS (
  postid BIGINT,
  tagid BIGINT,
  PRIMARY KEY (postid, tagid),
  FOREIGN KEY (postid) REFERENCES posts(postid),
  FOREIGN KEY (tagid) REFERENCES TAGS(id)

);



insert into posts (lilname,fullname,content) values ('Create new account','to add actual posts and comments','');
